globalThis.document={addEventListener(){},createElement:()=>({style:{},classList:{add(){},remove(){}},appendChild(){},focus(){}}),body:{appendChild(){}},getElementById:()=>null};
globalThis.window={};globalThis.Audio=function(){this.play=()=>Promise.resolve();this.pause=()=>{}};
const store={};globalThis.localStorage={getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=v,removeItem:k=>delete store[k]};
const BI=await import('/workspace/probe/rouge-offline/js/xiuxian/bestiary.js');
const B=await import('/workspace/probe/rouge-offline/js/xiuxian/build.js');
const F=await import('/workspace/probe/rouge-offline/js/xiuxian/family.js');
const C=await import('/workspace/probe/rouge-offline/js/xiuxian/camp.js');
const I=await import('/workspace/probe/rouge-offline/js/xiuxian/items.js');
let pass=0,fail=0;const t=(n,c)=>{c?pass++:(fail++,console.log('  ❌',n))};
const WIPE=()=>{for(const k of Object.keys(store))delete store[k];
  B.BUILD.s={placed:[],fires:[],land:[],tierLv:1,incomeAt:0,pacts:{signed:0,allyAt:0}};
  F.FAMILY.s={founded:false,name:'轩氏',members:[],couples:[],gen:1,wealth:0,land:[],mines:[],lastYield:0,attacks:0,defended:0};
  I.Bag.s={items:{},demon:0,charter:false}; C.setMomocha(false);};
const setup=()=>{WIPE();B.BUILD.setWorld(null);
  F.FAMILY.found('云氏'); F.FAMILY.s.wealth=99999;
  for(let i=0;i<3;i++)F.FAMILY.addMember('scholar');};

console.log('\n=== 灵米闭环 ===');
t('灵米有定义', !!BI.RICE && BI.RICE.name==='灵 米');
t('灵米可食用(有收益)', BI.RICE.eat.exp>0 && BI.RICE.eat.dao>0);
t('灵米可卖(有价)', BI.RICE.price>0);
t('灵米可喂人(有收益)', BI.RICE.feed.exp>0);
setup();
I.Bag.add('bld_field',1); B.BUILD.place('bld_field');
const h1=B.BUILD.harvest(0);
t('未种→点一下下种', h1.ok && /下种/.test(h1.msg));
t('种下后有倒计时', B.BUILD.s.placed[0].plantAt>Date.now());
const h2=B.BUILD.harvest(0);
t('未熟不能收', h2.ok===false);
B.BUILD.s.placed[0].plantAt=Date.now()-1;
const y0=B.BUILD.fieldYield(0);
B.BUILD.s.placed[0].workers.push({uid:F.FAMILY.s.members[1].uid,busy:true,at:Date.now()});
const h3=B.BUILD.harvest(0);
t('熟了能收(需有人)', h3.ok && h3.n>0);
t('收到背包里', I.Bag.count(BI.RICE.id)>0);
t('收完重置为未种', B.BUILD.s.placed[0].plantAt===0);
const e1=B.BUILD.eatRice(1);
t('生吞给修为', e1.ok && F.FAMILY.s.members.length>0);
// 补足灵米再测(收获量是随机的)
I.Bag.add(BI.RICE.id, 20);
const before=I.Bag.count(BI.RICE.id);
const s1=B.BUILD.sellRice(3);
t('能卖钱', s1.ok);
t('卖出扣数量', I.Bag.count(BI.RICE.id)===before-3);
I.Bag.add(BI.RICE.id, 10);
const m0=F.FAMILY.s.members.find(x=>x.npc!=='momocha');
B.BUILD.s.placed[0].workers=[{uid:m0.uid,busy:true,at:Date.now()}];
const lv0=F.FAMILY.member(m0.uid).lv;      // 取数值快照,不是引用
const rr=B.BUILD.feedRice(m0.uid,1);
t('喂族人涨层数', rr.ok && F.FAMILY.member(m0.uid).lv===lv0+1);
t('么么茶不吃饭', B.BUILD.feedRice(F.FAMILY.momocha().uid,1).ok===false);

console.log('\n=== 建筑差异化效果 ===');
WIPE(); B.BUILD.setWorld(null);
t('哨塔+护栏', BI.BUILDINGS.bld_tower.eff.ward>0);
t('哨塔有预警', BI.BUILDINGS.bld_tower.eff.warn===true);
t('议事堂+人口', BI.BUILDINGS.bld_hall.eff.popCap>0);
t('演武场+战力', BI.BUILDINGS.bld_barracks.eff.atk>0);
t('灵井+田产', BI.BUILDINGS.bld_well.eff.fieldMul>0);
t('集市可贸易', BI.BUILDINGS.bld_market.eff.trade===true);
t('五个都有 eff', ['bld_tower','bld_hall','bld_barracks','bld_well','bld_market']
  .every(k=>BI.BUILDINGS[k].eff && Object.keys(BI.BUILDINGS[k].eff).length>0));
F.FAMILY.found('x');
t('无建筑时护栏=0', B.BUILD.effects().ward===0);
I.Bag.add('bld_tower',1); B.BUILD.place('bld_tower');
t('建哨塔护栏+45', B.BUILD.effects().ward===45);
t('agg效果生效', B.BUILD.ward()>70);
I.Bag.add('bld_hall',1); B.BUILD.place('bld_hall');
t('议事堂人口上限+8', B.BUILD.popCap()===20);
I.Bag.add('bld_barracks',1); B.BUILD.place('bld_barracks');
const p0=B.BUILD.power();
WIPE(); F.FAMILY.found('y');
I.Bag.s.items={bld_well:1};
const wellP=B.BUILD.place('bld_well');
t('灵井能建', wellP.ok===true);
t('灵井灵田加成', B.BUILD.effects().fieldMul===0.5);
t('战力和演武场挂钩', p0>0);

console.log('\n=== 矿脉占领 ===');
WIPE();
F.FAMILY.found('x');
t('可占领秘境界', B.BUILD.claimMine('n4','secret').ok===true);
t('同处不能重复', B.BUILD.claimMine('n4','secret').ok===false);
t('村庄无矿', B.BUILD.claimMine('n0','village').ok===false);
t('篝火处不能占矿', (B.BUILD.addFire('n5'), B.BUILD.claimMine('n5','elite').ok===false));
B.BUILD.setWorld({nodes:[{id:'n4',type:'secret'},{id:'n7',type:'elite'}]});
I.Bag.add('stone_1',5);
C.CAMP.s={lit:true,nodeId:'n0',fuelEnd:Date.now()+3600000,totalSec:0,members:[],invites:0,formed:false,rep:0,lastTick:Date.now()};
const my=B.BUILD.mineYield();
t('火旺才开矿', my.n>0);
t('矿脉真给源石', I.Bag.count('stone_1')>5);

console.log('\n=== 阵法旗传送 ===');
WIPE(); F.FAMILY.found('x');
t('LV1不能传送', B.BUILD.canTeleport()===false);
B.BUILD.s.tierLv=2; B.BUILD.addFire('n0');
t('LV2+可传送', B.BUILD.canTeleport()===true);
t('传送有消耗', B.BUILD.teleportCost()>0);
F.FAMILY.s.founded=true;
const CULTA=(await import('/workspace/probe/rouge-offline/js/xiuxian/index.js')).Cult;
CULTA.get().dao=9999;
const tp=B.BUILD.teleportTo('n3');
t('传送成功', tp.ok && CULTA.get().current==='n3');
t('扣了道行', CULTA.get().dao<9999);
t('标记为已访问', CULTA.get().visited.n3===true);

console.log('\n=== 同盟契约 ===');
WIPE(); F.FAMILY.found('x');
const {Cult:CC}=await import('/workspace/probe/rouge-offline/js/xiuxian/index.js');
CC.get().dao=99999;
t('可订契约', B.BUILD.canPact()===true);
const pa=B.BUILD.signPact('落云散修');
t('缔结成功', pa.ok && B.BUILD.s.pacts.signed===1);
t('缔约耗道行', CC.get().dao<99999);
t('盟友会来', (()=>{const a=B.BUILD.allyAid();return a&&a.power>0})());
t('契约降围攻率', B.BUILD.pactShield()>0);
B.BUILD.signPact('青云'); B.BUILD.signPact('黑风');
t('最多3份', B.BUILD.canPact()===false);
t('第4份被拒', B.BUILD.signPact('x').ok===false);

console.log('\n=== 全属性修士 ===');
WIPE(); F.FAMILY.found('x'); F.FAMILY.s.wealth=3000;
const n0=F.FAMILY.s.members.length;
const r1=F.FAMILY.raise('sword');
t('养成成功', r1.ok && F.FAMILY.s.members.length===n0+1);
t('标记为 raised', r1.m.raised==='sword');
t('扣500资产', F.FAMILY.s.wealth===2500);
t('战力×3', (()=>{const p=F.FAMILY.power(); return p>=9})());
const y=F.FAMILY.yieldDay();
t('四项都产出', y.stone>0 && y.pill>0 && y.exp>0 && y.dao>0);
F.FAMILY.s.wealth=0;
t('没钱不能养', F.FAMILY.raise('body').ok===false);
t('4种可选', F.FAMILY.RAISED.length===4);
t('修士不可婚配', !r1.m.partner);

console.log(`\n${'='.repeat(48)}\n通过 ${pass} / 失败 ${fail}\n${'='.repeat(48)}`);